graduate to-hutohu
traPtitech/nss pull request #15
Opened 2020-03-31 10:39 UTC by tohutohu

卒業します！

2020-03-31 10:41 UTC, wtks requested changes
ついでに卒業してください

2020-03-31 10:41 UTC, wtks commented on cpctf.json
> +		"members": ["kaz", "FourmiSushi", "Nagarei"]
```suggestion
		"members": ["FourmiSushi", "Nagarei"]
```

2020-03-31 10:46 UTC, wtks approved these changes

2020-04-02 07:45 UTC, tohutohu commented
ping @FujishigeTemma

2020-04-03 12:25 UTC, merged