add lum1narie to sysad.json
traPtitech/nss pull request #34
Opened 2021-09-23 13:29 UTC by lum1narie

m011には事前に登録を行っていました

2021-09-23 13:33 UTC, hijiki51 requested changes

2021-09-23 13:33 UTC, hijiki51 commented on sysad.json
> +			"lum1narie"
ここ順番上と揃えてほしいです

2021-09-23 13:37 UTC, lum1narie commented
揃えてきました

2021-09-24 06:25 UTC, hijiki51 approved these changes

2021-09-24 06:25 UTC, merged