add hosshii
traPtitech/nss pull request #40
Opened 2022-01-26 14:46 UTC by Hosshii

お願いします🙏

2022-01-26 15:28 UTC, sapphi-red requested changes
> **ファイル間で使用するuid,gidは共通化すること**
> https://wiki.trap.jp/SysAd/linux-accounts

:pray:
https://github.com/traPtitech/nss/blob/d8feb6f94884521fdd02ce698d55ece0f0e6a0ba/sysad.json#L172-L188

2022-01-27 04:16 UTC, Hosshii commented
見逃してた🙏
修正しました

2022-01-27 06:45 UTC, sapphi-red reviewed
番号順になるようにしたほうがよさそう

2022-01-27 12:25 UTC, Hosshii commented
修正した
ついでに他のところも揃えました

2022-01-27 12:47 UTC, sapphi-red approved these changes
:kansya:

2022-01-27 12:47 UTC, merged