sysad.jsonにseigo2016を追加
traPtitech/nss pull request #59
Opened 2023-04-20 06:41 UTC by seigo2016

2023-05-01 12:44 UTC, ras0q requested changes
部外者です
インデントずれてそう

2023-05-01 13:20 UTC, seigo2016 commented
> 部外者です インデントずれてそう

あれ、どこがずれていますか…？
(比較したんですがわからず)

2023-05-01 13:25 UTC, ras0q commented
あれ、環境かな
![image](https://user-images.githubusercontent.com/66677201/235457703-4481d0dd-bfc3-438c-81e6-968578f9a640.png)

2023-05-01 13:28 UTC, seigo2016 commented
確かにどこかのcommitでその状態だった記憶はあるのですが、最新のは修正したはずです。(一応私の画面だとこうです)
どういうことでしょう…
![image](https://user-images.githubusercontent.com/25446804/235458062-e6559e59-8ae5-431a-ab84-9b8811f2d91f.png)

2023-05-01 16:01 UTC, hijiki51 commented
Soft Tab（空白インデント）じゃなくてHard Tab(タブ文字)にしてください

2023-05-11 08:40 UTC, seigo2016 commented
@hijiki51 遅くなりましてすみません。修正しました

2023-07-28 02:04 UTC, Takeno-hito approved these changes

2023-07-28 02:07 UTC, ras0q approved these changes

2023-09-07 04:15 UTC, merged