Add kentaro1043 to m011.json
traPtitech/nss pull request #87
Opened 2024-11-16 15:15 UTC by Kentaro1043

スクリプトの実行のためにプライベートネットワークのDBにアクセスする必要があるため
よろしくお願いします🙇

2024-11-16 15:17 UTC, Kentaro1043 commented
Wikiに追加しました

2024-11-17 15:03 UTC, cp-20 requested changes
sysadグループにも入れておいてください！ (一番下のところ)

2024-11-17 15:07 UTC, Kentaro1043 commented
やりました :eyes:

2024-11-17 15:07 UTC, cp-20 approved these changes

2024-11-17 15:07 UTC, merged